// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: buf/validate/conformance/cases/filename-with-dash.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Buf.Validate.Conformance.Cases {

  /// <summary>Holder for reflection information generated from buf/validate/conformance/cases/filename-with-dash.proto</summary>
  public static partial class FilenameWithDashReflection {

    #region Descriptor
    /// <summary>File descriptor for buf/validate/conformance/cases/filename-with-dash.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FilenameWithDashReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjdidWYvdmFsaWRhdGUvY29uZm9ybWFuY2UvY2FzZXMvZmlsZW5hbWUtd2l0",
            "aC1kYXNoLnByb3RvEh5idWYudmFsaWRhdGUuY29uZm9ybWFuY2UuY2FzZXMa",
            "G2J1Zi92YWxpZGF0ZS92YWxpZGF0ZS5wcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Buf.Validate.ValidateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
