// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: buf/validate/conformance/cases/subdirectory/in_subdirectory.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Buf.Validate.Conformance.Cases.Subdirectory {

  /// <summary>Holder for reflection information generated from buf/validate/conformance/cases/subdirectory/in_subdirectory.proto</summary>
  public static partial class InSubdirectoryReflection {

    #region Descriptor
    /// <summary>File descriptor for buf/validate/conformance/cases/subdirectory/in_subdirectory.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InSubdirectoryReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkFidWYvdmFsaWRhdGUvY29uZm9ybWFuY2UvY2FzZXMvc3ViZGlyZWN0b3J5",
            "L2luX3N1YmRpcmVjdG9yeS5wcm90bxIrYnVmLnZhbGlkYXRlLmNvbmZvcm1h",
            "bmNlLmNhc2VzLnN1YmRpcmVjdG9yeRobYnVmL3ZhbGlkYXRlL3ZhbGlkYXRl",
            "LnByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Buf.Validate.ValidateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
