// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: buf/validate/conformance/cases/kitchen_sink.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Buf.Validate.Conformance.Cases {

  /// <summary>Holder for reflection information generated from buf/validate/conformance/cases/kitchen_sink.proto</summary>
  public static partial class KitchenSinkReflection {

    #region Descriptor
    /// <summary>File descriptor for buf/validate/conformance/cases/kitchen_sink.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static KitchenSinkReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjFidWYvdmFsaWRhdGUvY29uZm9ybWFuY2UvY2FzZXMva2l0Y2hlbl9zaW5r",
            "LnByb3RvEh5idWYudmFsaWRhdGUuY29uZm9ybWFuY2UuY2FzZXMaG2J1Zi92",
            "YWxpZGF0ZS92YWxpZGF0ZS5wcm90bxoZZ29vZ2xlL3Byb3RvYnVmL2FueS5w",
            "cm90bxoeZ29vZ2xlL3Byb3RvYnVmL2R1cmF0aW9uLnByb3RvGh9nb29nbGUv",
            "cHJvdG9idWYvdGltZXN0YW1wLnByb3RvGh5nb29nbGUvcHJvdG9idWYvd3Jh",
            "cHBlcnMucHJvdG8ivAgKDkNvbXBsZXhUZXN0TXNnEiEKBWNvbnN0GAEgASgJ",
            "Qgu6SAhyBgoEYWJjZFIFY29uc3QSRgoGbmVzdGVkGAIgASgLMi4uYnVmLnZh",
            "bGlkYXRlLmNvbmZvcm1hbmNlLmNhc2VzLkNvbXBsZXhUZXN0TXNnUgZuZXN0",
            "ZWQSJAoJaW50X2NvbnN0GAMgASgFQge6SAQaAggFUghpbnRDb25zdBImCgpi",
            "b29sX2NvbnN0GAQgASgIQge6SARqAggAUglib29sQ29uc3QSRAoJZmxvYXRf",
            "dmFsGAUgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkZsb2F0VmFsdWVCCrpIBwoF",
            "JQAAAABSCGZsb2F0VmFsEkEKB2R1cl92YWwYBiABKAsyGS5nb29nbGUucHJv",
            "dG9idWYuRHVyYXRpb25CDbpICqoBBBoCCBHIAQFSBmR1clZhbBI9CgZ0c192",
            "YWwYByABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQgq6SAeyAQQq",
            "AggHUgV0c1ZhbBJICgdhbm90aGVyGAggASgLMi4uYnVmLnZhbGlkYXRlLmNv",
            "bmZvcm1hbmNlLmNhc2VzLkNvbXBsZXhUZXN0TXNnUgdhbm90aGVyEisKC2Zs",
            "b2F0X2NvbnN0GAkgASgCQgq6SAcKBRUAAABBUgpmbG9hdENvbnN0EjQKCWRv",
            "dWJsZV9pbhgKIAEoAUIXukgUEhIyELTIdr6fjHxAAAAAAADAXkBSCGRvdWJs",
            "ZUluElgKCmVudW1fY29uc3QYCyABKA4yLy5idWYudmFsaWRhdGUuY29uZm9y",
            "bWFuY2UuY2FzZXMuQ29tcGxleFRlc3RFbnVtQgi6SAWCAQIIAlIJZW51bUNv",
            "bnN0EmMKB2FueV92YWwYDCABKAsyFC5nb29nbGUucHJvdG9idWYuQW55QjS6",
            "SDGiAS4SLHR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnByb3RvYnVmLkR1",
            "cmF0aW9uUgZhbnlWYWwSSwoKcmVwX3RzX3ZhbBgNIAMoCzIaLmdvb2dsZS5w",
            "cm90b2J1Zi5UaW1lc3RhbXBCEbpIDpIBCyIJsgEGMgQQwIQ9UghyZXBUc1Zh",
            "bBJhCgdtYXBfdmFsGA4gAygLMjouYnVmLnZhbGlkYXRlLmNvbmZvcm1hbmNl",
            "LmNhc2VzLkNvbXBsZXhUZXN0TXNnLk1hcFZhbEVudHJ5Qgy6SAmaAQYiBDoC",
            "EABSBm1hcFZhbBImCglieXRlc192YWwYDyABKAxCCbpIBnoECgIAmVIIYnl0",
            "ZXNWYWwSDgoBeBgQIAEoCUgAUgF4Eg4KAXkYESABKAVIAFIBeRo5CgtNYXBW",
            "YWxFbnRyeRIQCgNrZXkYASABKBFSA2tleRIUCgV2YWx1ZRgCIAEoCVIFdmFs",
            "dWU6AjgBQgoKAW8SBbpIAggBIlYKEktpdGNoZW5TaW5rTWVzc2FnZRJACgN2",
            "YWwYASABKAsyLi5idWYudmFsaWRhdGUuY29uZm9ybWFuY2UuY2FzZXMuQ29t",
            "cGxleFRlc3RNc2dSA3ZhbCpqCg9Db21wbGV4VGVzdEVudW0SIQodQ09NUExF",
            "WF9URVNUX0VOVU1fVU5TUEVDSUZJRUQQABIZChVDT01QTEVYX1RFU1RfRU5V",
            "TV9PTkUQARIZChVDT01QTEVYX1RFU1RfRU5VTV9UV08QAmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Buf.Validate.ValidateReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.DurationReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Buf.Validate.Conformance.Cases.ComplexTestEnum), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Buf.Validate.Conformance.Cases.ComplexTestMsg), global::Buf.Validate.Conformance.Cases.ComplexTestMsg.Parser, new[]{ "Const", "Nested", "IntConst", "BoolConst", "FloatVal", "DurVal", "TsVal", "Another", "FloatConst", "DoubleIn", "EnumConst", "AnyVal", "RepTsVal", "MapVal", "BytesVal", "X", "Y" }, new[]{ "O" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Buf.Validate.Conformance.Cases.KitchenSinkMessage), global::Buf.Validate.Conformance.Cases.KitchenSinkMessage.Parser, new[]{ "Val" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ComplexTestEnum {
    [pbr::OriginalName("COMPLEX_TEST_ENUM_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("COMPLEX_TEST_ENUM_ONE")] One = 1,
    [pbr::OriginalName("COMPLEX_TEST_ENUM_TWO")] Two = 2,
  }

  #endregion

  #region Messages
  public sealed partial class ComplexTestMsg : pb::IMessage<ComplexTestMsg>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ComplexTestMsg> _parser = new pb::MessageParser<ComplexTestMsg>(() => new ComplexTestMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ComplexTestMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Buf.Validate.Conformance.Cases.KitchenSinkReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ComplexTestMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ComplexTestMsg(ComplexTestMsg other) : this() {
      const_ = other.const_;
      nested_ = other.nested_ != null ? other.nested_.Clone() : null;
      intConst_ = other.intConst_;
      boolConst_ = other.boolConst_;
      FloatVal = other.FloatVal;
      durVal_ = other.durVal_ != null ? other.durVal_.Clone() : null;
      tsVal_ = other.tsVal_ != null ? other.tsVal_.Clone() : null;
      another_ = other.another_ != null ? other.another_.Clone() : null;
      floatConst_ = other.floatConst_;
      doubleIn_ = other.doubleIn_;
      enumConst_ = other.enumConst_;
      anyVal_ = other.anyVal_ != null ? other.anyVal_.Clone() : null;
      repTsVal_ = other.repTsVal_.Clone();
      mapVal_ = other.mapVal_.Clone();
      bytesVal_ = other.bytesVal_;
      switch (other.OCase) {
        case OOneofCase.X:
          X = other.X;
          break;
        case OOneofCase.Y:
          Y = other.Y;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ComplexTestMsg Clone() {
      return new ComplexTestMsg(this);
    }

    /// <summary>Field number for the "const" field.</summary>
    public const int ConstFieldNumber = 1;
    private string const_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Const {
      get { return const_; }
      set {
        const_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nested" field.</summary>
    public const int NestedFieldNumber = 2;
    private global::Buf.Validate.Conformance.Cases.ComplexTestMsg nested_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Buf.Validate.Conformance.Cases.ComplexTestMsg Nested {
      get { return nested_; }
      set {
        nested_ = value;
      }
    }

    /// <summary>Field number for the "int_const" field.</summary>
    public const int IntConstFieldNumber = 3;
    private int intConst_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int IntConst {
      get { return intConst_; }
      set {
        intConst_ = value;
      }
    }

    /// <summary>Field number for the "bool_const" field.</summary>
    public const int BoolConstFieldNumber = 4;
    private bool boolConst_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool BoolConst {
      get { return boolConst_; }
      set {
        boolConst_ = value;
      }
    }

    /// <summary>Field number for the "float_val" field.</summary>
    public const int FloatValFieldNumber = 5;
    private static readonly pb::FieldCodec<float?> _single_floatVal_codec = pb::FieldCodec.ForStructWrapper<float>(42);
    private float? floatVal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float? FloatVal {
      get { return floatVal_; }
      set {
        floatVal_ = value;
      }
    }


    /// <summary>Field number for the "dur_val" field.</summary>
    public const int DurValFieldNumber = 6;
    private global::Google.Protobuf.WellKnownTypes.Duration durVal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Duration DurVal {
      get { return durVal_; }
      set {
        durVal_ = value;
      }
    }

    /// <summary>Field number for the "ts_val" field.</summary>
    public const int TsValFieldNumber = 7;
    private global::Google.Protobuf.WellKnownTypes.Timestamp tsVal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TsVal {
      get { return tsVal_; }
      set {
        tsVal_ = value;
      }
    }

    /// <summary>Field number for the "another" field.</summary>
    public const int AnotherFieldNumber = 8;
    private global::Buf.Validate.Conformance.Cases.ComplexTestMsg another_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Buf.Validate.Conformance.Cases.ComplexTestMsg Another {
      get { return another_; }
      set {
        another_ = value;
      }
    }

    /// <summary>Field number for the "float_const" field.</summary>
    public const int FloatConstFieldNumber = 9;
    private float floatConst_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float FloatConst {
      get { return floatConst_; }
      set {
        floatConst_ = value;
      }
    }

    /// <summary>Field number for the "double_in" field.</summary>
    public const int DoubleInFieldNumber = 10;
    private double doubleIn_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double DoubleIn {
      get { return doubleIn_; }
      set {
        doubleIn_ = value;
      }
    }

    /// <summary>Field number for the "enum_const" field.</summary>
    public const int EnumConstFieldNumber = 11;
    private global::Buf.Validate.Conformance.Cases.ComplexTestEnum enumConst_ = global::Buf.Validate.Conformance.Cases.ComplexTestEnum.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Buf.Validate.Conformance.Cases.ComplexTestEnum EnumConst {
      get { return enumConst_; }
      set {
        enumConst_ = value;
      }
    }

    /// <summary>Field number for the "any_val" field.</summary>
    public const int AnyValFieldNumber = 12;
    private global::Google.Protobuf.WellKnownTypes.Any anyVal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Any AnyVal {
      get { return anyVal_; }
      set {
        anyVal_ = value;
      }
    }

    /// <summary>Field number for the "rep_ts_val" field.</summary>
    public const int RepTsValFieldNumber = 13;
    private static readonly pb::FieldCodec<global::Google.Protobuf.WellKnownTypes.Timestamp> _repeated_repTsVal_codec
        = pb::FieldCodec.ForMessage(106, global::Google.Protobuf.WellKnownTypes.Timestamp.Parser);
    private readonly pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Timestamp> repTsVal_ = new pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Timestamp>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Google.Protobuf.WellKnownTypes.Timestamp> RepTsVal {
      get { return repTsVal_; }
    }

    /// <summary>Field number for the "map_val" field.</summary>
    public const int MapValFieldNumber = 14;
    private static readonly pbc::MapField<int, string>.Codec _map_mapVal_codec
        = new pbc::MapField<int, string>.Codec(pb::FieldCodec.ForSInt32(8, 0), pb::FieldCodec.ForString(18, ""), 114);
    private readonly pbc::MapField<int, string> mapVal_ = new pbc::MapField<int, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, string> MapVal {
      get { return mapVal_; }
    }

    /// <summary>Field number for the "bytes_val" field.</summary>
    public const int BytesValFieldNumber = 15;
    private pb::ByteString bytesVal_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString BytesVal {
      get { return bytesVal_; }
      set {
        bytesVal_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 16;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string X {
      get { return HasX ? (string) o_ : ""; }
      set {
        o_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        oCase_ = OOneofCase.X;
      }
    }
    /// <summary>Gets whether the "x" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasX {
      get { return oCase_ == OOneofCase.X; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "x" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearX() {
      if (HasX) {
        ClearO();
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 17;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Y {
      get { return HasY ? (int) o_ : 0; }
      set {
        o_ = value;
        oCase_ = OOneofCase.Y;
      }
    }
    /// <summary>Gets whether the "y" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasY {
      get { return oCase_ == OOneofCase.Y; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "y" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearY() {
      if (HasY) {
        ClearO();
      }
    }

    private object o_;
    /// <summary>Enum of possible cases for the "o" oneof.</summary>
    public enum OOneofCase {
      None = 0,
      X = 16,
      Y = 17,
    }
    private OOneofCase oCase_ = OOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OOneofCase OCase {
      get { return oCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearO() {
      oCase_ = OOneofCase.None;
      o_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ComplexTestMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ComplexTestMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Const != other.Const) return false;
      if (!object.Equals(Nested, other.Nested)) return false;
      if (IntConst != other.IntConst) return false;
      if (BoolConst != other.BoolConst) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.Equals(FloatVal, other.FloatVal)) return false;
      if (!object.Equals(DurVal, other.DurVal)) return false;
      if (!object.Equals(TsVal, other.TsVal)) return false;
      if (!object.Equals(Another, other.Another)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(FloatConst, other.FloatConst)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DoubleIn, other.DoubleIn)) return false;
      if (EnumConst != other.EnumConst) return false;
      if (!object.Equals(AnyVal, other.AnyVal)) return false;
      if(!repTsVal_.Equals(other.repTsVal_)) return false;
      if (!MapVal.Equals(other.MapVal)) return false;
      if (BytesVal != other.BytesVal) return false;
      if (X != other.X) return false;
      if (Y != other.Y) return false;
      if (OCase != other.OCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Const.Length != 0) hash ^= Const.GetHashCode();
      if (nested_ != null) hash ^= Nested.GetHashCode();
      if (IntConst != 0) hash ^= IntConst.GetHashCode();
      if (BoolConst != false) hash ^= BoolConst.GetHashCode();
      if (floatVal_ != null) hash ^= pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.GetHashCode(FloatVal);
      if (durVal_ != null) hash ^= DurVal.GetHashCode();
      if (tsVal_ != null) hash ^= TsVal.GetHashCode();
      if (another_ != null) hash ^= Another.GetHashCode();
      if (FloatConst != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(FloatConst);
      if (DoubleIn != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DoubleIn);
      if (EnumConst != global::Buf.Validate.Conformance.Cases.ComplexTestEnum.Unspecified) hash ^= EnumConst.GetHashCode();
      if (anyVal_ != null) hash ^= AnyVal.GetHashCode();
      hash ^= repTsVal_.GetHashCode();
      hash ^= MapVal.GetHashCode();
      if (BytesVal.Length != 0) hash ^= BytesVal.GetHashCode();
      if (HasX) hash ^= X.GetHashCode();
      if (HasY) hash ^= Y.GetHashCode();
      hash ^= (int) oCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Const.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Const);
      }
      if (nested_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Nested);
      }
      if (IntConst != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(IntConst);
      }
      if (BoolConst != false) {
        output.WriteRawTag(32);
        output.WriteBool(BoolConst);
      }
      if (floatVal_ != null) {
        _single_floatVal_codec.WriteTagAndValue(output, FloatVal);
      }
      if (durVal_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(DurVal);
      }
      if (tsVal_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(TsVal);
      }
      if (another_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Another);
      }
      if (FloatConst != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(FloatConst);
      }
      if (DoubleIn != 0D) {
        output.WriteRawTag(81);
        output.WriteDouble(DoubleIn);
      }
      if (EnumConst != global::Buf.Validate.Conformance.Cases.ComplexTestEnum.Unspecified) {
        output.WriteRawTag(88);
        output.WriteEnum((int) EnumConst);
      }
      if (anyVal_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(AnyVal);
      }
      repTsVal_.WriteTo(output, _repeated_repTsVal_codec);
      mapVal_.WriteTo(output, _map_mapVal_codec);
      if (BytesVal.Length != 0) {
        output.WriteRawTag(122);
        output.WriteBytes(BytesVal);
      }
      if (HasX) {
        output.WriteRawTag(130, 1);
        output.WriteString(X);
      }
      if (HasY) {
        output.WriteRawTag(136, 1);
        output.WriteInt32(Y);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Const.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Const);
      }
      if (nested_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Nested);
      }
      if (IntConst != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(IntConst);
      }
      if (BoolConst != false) {
        output.WriteRawTag(32);
        output.WriteBool(BoolConst);
      }
      if (floatVal_ != null) {
        _single_floatVal_codec.WriteTagAndValue(ref output, FloatVal);
      }
      if (durVal_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(DurVal);
      }
      if (tsVal_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(TsVal);
      }
      if (another_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(Another);
      }
      if (FloatConst != 0F) {
        output.WriteRawTag(77);
        output.WriteFloat(FloatConst);
      }
      if (DoubleIn != 0D) {
        output.WriteRawTag(81);
        output.WriteDouble(DoubleIn);
      }
      if (EnumConst != global::Buf.Validate.Conformance.Cases.ComplexTestEnum.Unspecified) {
        output.WriteRawTag(88);
        output.WriteEnum((int) EnumConst);
      }
      if (anyVal_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(AnyVal);
      }
      repTsVal_.WriteTo(ref output, _repeated_repTsVal_codec);
      mapVal_.WriteTo(ref output, _map_mapVal_codec);
      if (BytesVal.Length != 0) {
        output.WriteRawTag(122);
        output.WriteBytes(BytesVal);
      }
      if (HasX) {
        output.WriteRawTag(130, 1);
        output.WriteString(X);
      }
      if (HasY) {
        output.WriteRawTag(136, 1);
        output.WriteInt32(Y);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Const.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Const);
      }
      if (nested_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Nested);
      }
      if (IntConst != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IntConst);
      }
      if (BoolConst != false) {
        size += 1 + 1;
      }
      if (floatVal_ != null) {
        size += _single_floatVal_codec.CalculateSizeWithTag(FloatVal);
      }
      if (durVal_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DurVal);
      }
      if (tsVal_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TsVal);
      }
      if (another_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Another);
      }
      if (FloatConst != 0F) {
        size += 1 + 4;
      }
      if (DoubleIn != 0D) {
        size += 1 + 8;
      }
      if (EnumConst != global::Buf.Validate.Conformance.Cases.ComplexTestEnum.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EnumConst);
      }
      if (anyVal_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AnyVal);
      }
      size += repTsVal_.CalculateSize(_repeated_repTsVal_codec);
      size += mapVal_.CalculateSize(_map_mapVal_codec);
      if (BytesVal.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(BytesVal);
      }
      if (HasX) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(X);
      }
      if (HasY) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Y);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ComplexTestMsg other) {
      if (other == null) {
        return;
      }
      if (other.Const.Length != 0) {
        Const = other.Const;
      }
      if (other.nested_ != null) {
        if (nested_ == null) {
          Nested = new global::Buf.Validate.Conformance.Cases.ComplexTestMsg();
        }
        Nested.MergeFrom(other.Nested);
      }
      if (other.IntConst != 0) {
        IntConst = other.IntConst;
      }
      if (other.BoolConst != false) {
        BoolConst = other.BoolConst;
      }
      if (other.floatVal_ != null) {
        if (floatVal_ == null || other.FloatVal != 0F) {
          FloatVal = other.FloatVal;
        }
      }
      if (other.durVal_ != null) {
        if (durVal_ == null) {
          DurVal = new global::Google.Protobuf.WellKnownTypes.Duration();
        }
        DurVal.MergeFrom(other.DurVal);
      }
      if (other.tsVal_ != null) {
        if (tsVal_ == null) {
          TsVal = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        TsVal.MergeFrom(other.TsVal);
      }
      if (other.another_ != null) {
        if (another_ == null) {
          Another = new global::Buf.Validate.Conformance.Cases.ComplexTestMsg();
        }
        Another.MergeFrom(other.Another);
      }
      if (other.FloatConst != 0F) {
        FloatConst = other.FloatConst;
      }
      if (other.DoubleIn != 0D) {
        DoubleIn = other.DoubleIn;
      }
      if (other.EnumConst != global::Buf.Validate.Conformance.Cases.ComplexTestEnum.Unspecified) {
        EnumConst = other.EnumConst;
      }
      if (other.anyVal_ != null) {
        if (anyVal_ == null) {
          AnyVal = new global::Google.Protobuf.WellKnownTypes.Any();
        }
        AnyVal.MergeFrom(other.AnyVal);
      }
      repTsVal_.Add(other.repTsVal_);
      mapVal_.MergeFrom(other.mapVal_);
      if (other.BytesVal.Length != 0) {
        BytesVal = other.BytesVal;
      }
      switch (other.OCase) {
        case OOneofCase.X:
          X = other.X;
          break;
        case OOneofCase.Y:
          Y = other.Y;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Const = input.ReadString();
            break;
          }
          case 18: {
            if (nested_ == null) {
              Nested = new global::Buf.Validate.Conformance.Cases.ComplexTestMsg();
            }
            input.ReadMessage(Nested);
            break;
          }
          case 24: {
            IntConst = input.ReadInt32();
            break;
          }
          case 32: {
            BoolConst = input.ReadBool();
            break;
          }
          case 42: {
            float? value = _single_floatVal_codec.Read(input);
            if (floatVal_ == null || value != 0F) {
              FloatVal = value;
            }
            break;
          }
          case 50: {
            if (durVal_ == null) {
              DurVal = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            input.ReadMessage(DurVal);
            break;
          }
          case 58: {
            if (tsVal_ == null) {
              TsVal = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TsVal);
            break;
          }
          case 66: {
            if (another_ == null) {
              Another = new global::Buf.Validate.Conformance.Cases.ComplexTestMsg();
            }
            input.ReadMessage(Another);
            break;
          }
          case 77: {
            FloatConst = input.ReadFloat();
            break;
          }
          case 81: {
            DoubleIn = input.ReadDouble();
            break;
          }
          case 88: {
            EnumConst = (global::Buf.Validate.Conformance.Cases.ComplexTestEnum) input.ReadEnum();
            break;
          }
          case 98: {
            if (anyVal_ == null) {
              AnyVal = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(AnyVal);
            break;
          }
          case 106: {
            repTsVal_.AddEntriesFrom(input, _repeated_repTsVal_codec);
            break;
          }
          case 114: {
            mapVal_.AddEntriesFrom(input, _map_mapVal_codec);
            break;
          }
          case 122: {
            BytesVal = input.ReadBytes();
            break;
          }
          case 130: {
            X = input.ReadString();
            break;
          }
          case 136: {
            Y = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Const = input.ReadString();
            break;
          }
          case 18: {
            if (nested_ == null) {
              Nested = new global::Buf.Validate.Conformance.Cases.ComplexTestMsg();
            }
            input.ReadMessage(Nested);
            break;
          }
          case 24: {
            IntConst = input.ReadInt32();
            break;
          }
          case 32: {
            BoolConst = input.ReadBool();
            break;
          }
          case 42: {
            float? value = _single_floatVal_codec.Read(ref input);
            if (floatVal_ == null || value != 0F) {
              FloatVal = value;
            }
            break;
          }
          case 50: {
            if (durVal_ == null) {
              DurVal = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            input.ReadMessage(DurVal);
            break;
          }
          case 58: {
            if (tsVal_ == null) {
              TsVal = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(TsVal);
            break;
          }
          case 66: {
            if (another_ == null) {
              Another = new global::Buf.Validate.Conformance.Cases.ComplexTestMsg();
            }
            input.ReadMessage(Another);
            break;
          }
          case 77: {
            FloatConst = input.ReadFloat();
            break;
          }
          case 81: {
            DoubleIn = input.ReadDouble();
            break;
          }
          case 88: {
            EnumConst = (global::Buf.Validate.Conformance.Cases.ComplexTestEnum) input.ReadEnum();
            break;
          }
          case 98: {
            if (anyVal_ == null) {
              AnyVal = new global::Google.Protobuf.WellKnownTypes.Any();
            }
            input.ReadMessage(AnyVal);
            break;
          }
          case 106: {
            repTsVal_.AddEntriesFrom(ref input, _repeated_repTsVal_codec);
            break;
          }
          case 114: {
            mapVal_.AddEntriesFrom(ref input, _map_mapVal_codec);
            break;
          }
          case 122: {
            BytesVal = input.ReadBytes();
            break;
          }
          case 130: {
            X = input.ReadString();
            break;
          }
          case 136: {
            Y = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class KitchenSinkMessage : pb::IMessage<KitchenSinkMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<KitchenSinkMessage> _parser = new pb::MessageParser<KitchenSinkMessage>(() => new KitchenSinkMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<KitchenSinkMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Buf.Validate.Conformance.Cases.KitchenSinkReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KitchenSinkMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KitchenSinkMessage(KitchenSinkMessage other) : this() {
      val_ = other.val_ != null ? other.val_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public KitchenSinkMessage Clone() {
      return new KitchenSinkMessage(this);
    }

    /// <summary>Field number for the "val" field.</summary>
    public const int ValFieldNumber = 1;
    private global::Buf.Validate.Conformance.Cases.ComplexTestMsg val_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Buf.Validate.Conformance.Cases.ComplexTestMsg Val {
      get { return val_; }
      set {
        val_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as KitchenSinkMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(KitchenSinkMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Val, other.Val)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (val_ != null) hash ^= Val.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (val_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Val);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (val_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Val);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (val_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Val);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(KitchenSinkMessage other) {
      if (other == null) {
        return;
      }
      if (other.val_ != null) {
        if (val_ == null) {
          Val = new global::Buf.Validate.Conformance.Cases.ComplexTestMsg();
        }
        Val.MergeFrom(other.Val);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (val_ == null) {
              Val = new global::Buf.Validate.Conformance.Cases.ComplexTestMsg();
            }
            input.ReadMessage(Val);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (val_ == null) {
              Val = new global::Buf.Validate.Conformance.Cases.ComplexTestMsg();
            }
            input.ReadMessage(Val);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
