<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <StartupObject>ProtoValidate.Conformance.Program</StartupObject>
        <OutputType>Exe</OutputType>
        <PlatformTarget>x64</PlatformTarget>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <SelfContained>false</SelfContained>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="proto\test.proto" />
        <None Remove="Tests\Data\conformance.pbbin" />
        <None Remove="Tests\Data\numbers.json" />
        <None Remove="Tests\Data\numbers.pbbin" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="proto\test.proto">
        <PackagePath>content/proto</PackagePath>
        <Pack>true</Pack>
      </Content>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Tests\Data\conformance.pbbin" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
        <PackageReference Include="NUnit" Version="3.14.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\ProtoValidate\ProtoValidate.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="proto\buf\NewFolder\" />
    </ItemGroup>

</Project>