name: Run Conformance Tests

on:  
  pull_request:
    branches: [main]
  workflow_dispatch: {} # support manual runs

permissions:
  contents: read  

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:        
        os: [ubuntu-latest, windows-2019]        

    steps:
      - uses: actions/checkout@v4      
      
      - name: Setup dotnet 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Setup dotnet 7.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'       
                    
      - name: Setup dotnet 8.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'   
      
      - name: Display dotnet version
        run: dotnet --version
      
      - name: Display Make version
        run: make --version        

      - name: Build ProtoValidate
        run: dotnet msbuild "-t:Restore;Build;PublishAll" "-p:Configuration=Release"

      - name: Run Conformance (Windows .Net 8.0)
        if: runner.os == 'windows'
        run: make conformance-mingw-net80

      - name: Run Conformance (Windows .Net 7.0)
        if: runner.os == 'windows'
        run: make conformance-mingw-net70

      - name: Run Conformance (Windows .Net 6.0)
        if: runner.os == 'windows'
        run: make conformance-mingw-net60

      - name: Run Conformance (Windows .Net 4.8)
        if: runner.os == 'windows'
        run: make conformance-mingw-net48

      - name: Run Conformance (Linux .Net 6.0)
        if: runner.os == 'linux'
        run: make conformance-linux-net60

      - name: Run Conformance (Linux .Net 7.0)
        if: runner.os == 'linux'
        run: make conformance-linux-net70

      - name: Run Conformance (Linux .Net 8.0)
        if: runner.os == 'linux'
        run: make conformance-linux-net80
