name: Run Conformance Tests

on:
  push:    
  pull_request:
    branches: [main]
  workflow_dispatch: {} # support manual runs

permissions:
  contents: read  

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]
        os: [ubuntu-latest, windows-latest]        

    steps:
      - uses: actions/checkout@v4      
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}      
      - name: Display dotnet version
        run: dotnet --version
      - name: Display Make version
        run: make --version        

      - name: Build ProtoValidate
        run: dotnet msbuild "-t:Restore;Build;PublishAll" "-p:Configuration=Release"

      - name: Run Conformance (Windows .Net 4.8)
        if: runner.os == 'windows'
        run: make conformance-mingw-net48      

      - name: Run Conformance (Windows .Net 6.0)
        if: runner.os == 'windows'
        run: make conformance-mingw-net60

      - name: Run Conformance (Windows .Net 7.0)
        if: runner.os == 'windows'
        run: make conformance-mingw-net70

      - name: Run Conformance (Windows .Net 8.0)
        if: runner.os == 'windows'
        run: make conformance-mingw-net80 

      - name: Run Conformance (Linux .Net 6.0)
        if: runner.os == 'linux'
        run: make conformance-linux-net60

      - name: Run Conformance (Linux .Net 7.0)
        if: runner.os == 'linux'
        run: make conformance-linux-net70

      - name: Run Conformance (Linux .Net 8.0)
        if: runner.os == 'linux'
        run: make conformance-linux-net80
